version: '3'

services:

  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-storage:/loki
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana    

  
  

volumes:
  grafana-storage:
  loki-storage:
